### ISSUE TITLE
Using single relay for testing relay (testing using multiple profiles) does not work with one or more nostr clients

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#22]
## client initiating action

coracle

## client receiving or observing action (or lack thereof)

coracle

## timestamp

@mleku

https://njump.me/nevent1qqsys0e9e4mwk2pl3lh8fd7lrrxlqnsj5cr0evxuch70tt8yw4l6q4cpzamhxue69uhkxcfwdaexzmn8v4cxjmrv9ejx2aspz4mhxue69uhkummnw3ezu6twdaehgcfwvd3sz9nhwden5te0wfk8jtnwdaehguntd9jzucm0d5q3xamnwvaz7tmjv4kxz7tpvfkx2tn0wfnstuvclh

## what happens 

> there is a really big problem brewing in #nostr   

> there is no client to test a relay with

> the clients all have logic to try other relays all the time for whatever reasons

> the clients don't show clear information about the status of connections with relays

> the clients for whatever reason decline to send messages to the relays

> i set up three users all connected to one relay and have them all follow each other and nothing comes up on the #coracle  feed page, though i can copy the links to the posts each one makes and see them in the others

> how can i test that my relay works if the client assumes it can't rely on one relay to see events?

> i tried to talk some sense into @mikedilger  about this, about how his gossip client refuses to respect any kind of settings for choice of relays and @hodlbod  's client is almost good with NIP-42 but fails because it's running off on its own picking relays to talk to

> EVEN WHEN I HAVE SET ONLY ONE AND SET ONLY ONE IN FORCE_RELAYS

> there is no way to test a relay standalone in this entire ecosystem right now

> you can't be sure your relay is working, it's not possible to be sure it's working, the client doesn't let you be sure, none of them

> if anyone knows of a client that does, i'm all ears but at this point it looks to me like i'm going to be building a basic CLI client so i can at least depend on it

**Comment by staab** [comment]
FORCE_RELAYS works as intended (except when initially logging in), I welcome evidence to the contrary.

**Comment by mleku** [comment]
> FORCE_RELAYS works as intended (except when initially logging in), I welcome evidence to the contrary.

it works on and off, it's very patchy at best, and definitely stops working when only one relay is set in all the fields of .env

i've lost patience with trying to get it to work properly, i was making a chat bot and because of the need for it to auth and the lack of full support of that, likely due to it not respecting my relay settings, i have given up and i can make nostrudel work perfectly, instantly propagating DMs and notes between 3 separate accounts in 3 separate browse profiles with very little difficulty

i'm fine to not use coracle as my test rig, just letting you know you can't use it this way, but it's great for end users

**Comment by staab** [comment]
Cool, I'll look into it. Relay selections desperately need to be refactored.
