### ISSUE TITLE
Ditto malformed "e" tags

### ISSUE THREAD

**Issue by eskema** [nostrability/nostrability#52]
## client initiating action
Ditto (or whatever client Alex Gleason uses nostr with)

## what happens 
Ditto adds "e" tags markers (root,reply) at index `2` instead of `3` where relay url should be.

## suggestion
add an empty string to tag array if no relay url is found.

example: note1k3tu38rz8gkfjgddm9hm4jcluu9xt9l2nmcp4agkmns3mvnneklqy38pqp

**Comment by alltheseas** [comment]
@alexgleason

**Comment by alexgleason** [comment]
Whoops! Thank you for the heads up, I will fix this. cc @patrickreiis

**Comment by alexgleason** [comment]
Fixed by https://gitlab.com/soapbox-pub/ditto/-/merge_requests/413

Here is a new event to demonstrate it working: https://njump.me/nevent1qqswd0t3d2nnfx759wrra3y40ava22nx5aquqhhh6k7mc2swzr6q2vszyqzxrl97e3xrxazrnyeddw83zf5uekmue9e667js4cmzmvf4536d6m576vz

I also took the opportunity to add relay hints throughout.

Thank you very much for discovering and reporting this @eskema !
